### PR TITLE
Reimplement interface checker

### LINKED ISSUE #4: Flag incomplete implementation on class def instead of instantiation?
From the README:

```py
class IAnimal(zope.interface.Interface):
    def say() -> None:
        pass

@zope.interface.implementer(IAnimal)
class Cow(object):
    def say(self) -> None:
        print("Moooo")
```
> The interface IAnimal will be treated as an abstract base class of the implementation Cow: you will not be able to instantiate Cow if interface implementation is incomplete. Incompatible method signatures will be reported as well.

If `Cow` states it implements `IAnimal`, and it doesn't implement `say()`, wouldn't that be an error even if `Cow` is never instantiated? In other words, I think this error could reported on the class definition instead of on instantiation.

Reporting the error on the implementer's class definition would be an advantage in code bases that don't have 100% type checking coverage: if the code that instantiates the implementer is inside a function that lacks type annotations, mypy will skip that code and the incomplete interface implementation will not be reported.

### LINKED ISSUE #7: TypeError: interpreted classes cannot inherit from compiled
CI is failing, and I believe this means that this plugin doesn't support the current version of mypy.  So one bug here is just that `setup.py` is insufficiently restrictive as the code stands today; it needs an upper bound on mypy versions.  But as I recall this is an upstream incompatibility introduced in mypy - which version does it break in, and does this require changes in mypy to start working again or is it something this plugin should change?

### PR DESCRIPTION
**Pull request by kedder**
Instead of simulating interfaces with inheritance or protocols and relying on mypy internals to verify valid implementation, implement own interface checking routine.

Every time we find an implementation, declared with `@zope.interface.implementer` decorator, we will check that implementation for compatibility with given interface.

Fixes #7 
Fixes #4

### CODE REVIEW

**Comment by glyph** [comment]
Wow. Thank you for all your work on this. Very cool!

**Comment by glyph** [comment]
(Does this new checker have a PyPI release yet?)

**Comment by kedder** [comment]
Yep, it is released as mypy-zope-0.2.0: https://pypi.org/project/mypy-zope/

**Comment by glyph** [comment]
@kedder Thank you for all your work on this!

**Pull request merged**
