### PR TITLE
Add supoort for Python 3.12 & 3.13 and update mypy dependancy

### PR DESCRIPTION
**Pull request by pmisik**

### CODE REVIEW

**Comment by pmisik** [comment]
@kedder
Can you please review this PR once you have time?
I hope this PR should address newer Python and latest mypy.

**Comment by kedder** [comment]
Thank you! I'll release a new version shortly.

**Review by kedder — APPROVED** [review]

**Comment by kedder** [comment]
[mypy-zope-1.0.6](https://pypi.org/project/mypy-zope/1.0.6/) is out.

**Comment by pmisik** [comment]
You can close https://github.com/Shoobx/mypy-zope/pull/117 now.

**Pull request merged**
